language: node_js

node_js:
  - node

env:
  global: PATH=/opt/python/3.7.1/bin:$PATH

notifications:
  email: false

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules

# install dependenices
before-script:
  - npm install

# on PRs and merges to master and prod run tests and build the app
script:
  - npm run test

# only run this script on pull requests and merges into
# the 'master' branches
branches:
  only:
    - master
